on:
  pull_request:
  push:
    paths:
      - ".github/workflows/build.yml"
      - "src/**"
      - "src-devtool/**"
      - "xmake.lua"
  workflow_dispatch:

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      src: ${{ steps.filter.outputs.src }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            src:
              - '.github/workflows/build.yml'
              - 'src/**'
              - 'src-devtool/**'
              - 'xmake.lua'

  build:
    needs: changes
    if: needs.changes.outputs.src == 'true' || github.event_name == 'workflow_dispatch'
    runs-on: windows-latest
    strategy:
      matrix:
        devtool: ["y", "n"]
    name: build-${{ matrix.devtool == 'y' && 'devtool' || 'headless' }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: xmake-io/github-action-setup-xmake@v1
        # with:
        #   xmake-version: "2.9.9"

      - uses: actions/cache@v4
        with:
          path: |
            ~/AppData/Local/.xmake
          key: xmake-${{ hashFiles('xmake.lua') }}
          restore-keys: |
            xmake-
  
      - name: Setup LLVM
        uses: ZhongRuoyu/setup-llvm@v0
        with:
          llvm-version: 22

      - run: |
          xmake repo -u

      - run: |
          xmake f -a x64 -m release -p windows -v -y --devtool=${{ matrix.devtool }}

      - run: |
          xmake -v -y

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.repository.name }}-windows-x64-${{ matrix.devtool == 'y' && 'devtool' || 'headless' }}-${{ github.sha }}
          path: |
            bin/

  build-gate:
    name: build-gate
    needs: [changes, build]
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Validate build status
        run: |
          SRC_CHANGE=${{ needs.changes.outputs.src }}
          EVENT=${{ github.event_name }}
          if [[ "$SRC_CHANGE" == "true" || "$EVENT" == "workflow_dispatch" ]]; then
            if [[ "${{ needs.build.result }}" != "success" ]]; then
              echo "❌ Build matrix failed/cancelled"
              exit 1
            fi
          fi
          echo "✅ Check passed: no source changes or build succeeded"
