on:
  release:
    types:
      - published

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        devtool: ["y", "n"]
    name: build-${{ matrix.devtool == 'y' && 'devtool' || 'headless' }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: xmake-io/github-action-setup-xmake@v1
        # with:
        #   xmake-version: "2.9.9"

      - uses: actions/cache@v4
        with:
          path: |
            ~/AppData/Local/.xmake
          key: xmake-${{ hashFiles('xmake.lua') }}
          restore-keys: |
            xmake-

      - name: Setup LLVM
        uses: ZhongRuoyu/setup-llvm@v0
        with:
          llvm-version: 22

      - name: Install scripting deps
        run: |
          npm install -g typescript
          curl -L -o qjsc.exe "https://github.com/engsr6982/quickjs-ng/releases/download/v0.15.1/qjsc.exe"
          ls
          where.exe tsc
          where.exe qjsc
          tsc --version

      - run: |
          xmake repo -u

      - run: |
          xmake f -a x64 -m release -p windows -v -y --devtool=${{ matrix.devtool }}

      - run: |
          xmake -w -y

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.repository.name }}-windows-x64-${{ matrix.devtool == 'y' && 'devtool' || 'headless' }}-${{ github.sha }}
          path: |
            bin/

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.repository.name }}-scripts-debug-bundle-${{ github.sha }}
          path: |
            build/.dist
            build/.qjsc
            src-scripts/

  update-release-notes:
    outputs:
      release_notes: ${{ steps.extract-release-notes.outputs.release_notes }}
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - id: extract-release-notes
        uses: ffurrer2/extract-release-notes@v2

      - uses: softprops/action-gh-release@v1
        with:
          body: |-
            ${{ steps.extract-release-notes.outputs.release_notes }}

  upload-to-release:
    needs:
      - build
      - update-release-notes
    permissions:
      contents: write
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - variant: windows-x64-devtool
          - variant: windows-x64-headless
          - variant: scripts-debug-bundle
    env:
      FinalName: ${{ github.event.repository.name }}-${{ matrix.variant }}
      ArtifactName: ${{ github.event.repository.name }}-${{ matrix.variant }}-${{ github.sha }}
    name: upload-to-release-${{ matrix.variant }}
    steps:
      - run: |
          echo "FinalName: ${{ env.FinalName }}"
          echo "ArtifactName: ${{ env.ArtifactName }}"

      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: ${{ env.ArtifactName }}
          path: artifact

      - run: |
          cp CHANGELOG.md README.md LICENSE artifact/

      - run: |
          zip -r ../${{ env.FinalName }}.zip *
        working-directory: artifact

      - uses: softprops/action-gh-release@v1
        with:
          append_body: true
          files: |
            ${{ env.FinalName }}.zip